### ISSUE TITLE
Want to know clear brief

### ISSUE THREAD

**Issue by milanshresta** [bishaller/jug#1]

**Comment by bishaller** [comment]
@milanshresta 

Do you need any help in this? 

This is a project that I did long time ago when I was immature coder. So, please bare with me.
However, this uses [gulp](https://gulpjs.com/docs/en/getting-started/quick-start/) as a code compiler for html/css/js and can be integrated to any other projects.

So, to run this project, you need to have a gulp CLI in your local machine and node v14.
then, just run npm install and then gulp. This will run the project.

However, we also need a local server to run the project. I used mamp for this, but you can find alternatives. And, the url used in the local server should be the same in gulpfile.js.

After that, the localhost:3000 imitates the url to render your code.

However, I would suggest to use webpack instead of gulp. As gulp has a ton of limitations and this project is not feasible for me at this point of time.
